name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python runtime
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install application dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Log in to DockerHub registry
      run: |
        echo "dckr_pat_yzr5pr_z_Iyi-EKPVXMmWCqvZu0" | docker login -u "sandip6502" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t sandip6502/devops-app:latest .
        docker push sandip6502/devops-app:latest
        
